spring.application.name=url-shortner-sb

spring.datasource.url = jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username = postgres
spring.datasource.password = satyam0346
spring.datasource.driver-class-name = org.postgresql.Driver