spring.application.name=url-shortner-sb

spring.datasource.url = jdbc:postgresql://loacalhost:5432/url_shortner
spring.datasource.username = postgres
spring.datasource.password = satyam0346
spring.datasource.driver-class-name = org.postgresql.Driver